name: glycotools
channels:
- conda-forge
dependencies:
- python>=3.7
- matplotlib=3.9.2
- rdkit=2021.03.5
- conda-minify=0.1.2
- numpy=1.26.4
- pandas=1.0.3
- pandas-flavor=0.6.0
- pip>=20.0.2
- pytorch>=2.4.0
- scikit-learn=1.3.2
- scipy=1.13.1
- pip=21.2.*
- ipykernel=6.0.*
- rxnmapper=0.3.1

